org.gradle.jvmargs=-Xmx10g -Xms7g -XX:+HeapDumpOnOutOfMemoryError -XX:GCTimeLimit=10 -XX:GCHeapFreeLimit=90 -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.tooling.parallel=true
org.gradle.java.installations.auto-download=false
kotlin.daemon.jvmargs=-Xmx6g -Xms256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
org.gradle.unsafe.isolated-projects=true
